version: 2
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby:
        - javascript:
  eslint:
    enabled: true
  fixme:
    enabled: true

exclude_patterns:
- config/
- db/
- vendor/
- log/
- bin/
- test/


