env: flex
runtime: custom

manual_scaling:
  instances: 3

resources:
  cpu: 1
  memory_gb: 4

env_variables:
  AWS_ACCESS_KEY_ID: $_AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $_AWS_SECRET_ACCESS_KEY
  DB_USER: $_DB_USER
  DB_PASS: $_DB_PASS
  DB_NAME: $_DB_NAME
  DB_HOST: $_DB_HOST
  DB_SOCKET: $_DB_SOCKET
  RAILS_ENV: $_RAILS_ENV
  RECAPTCHA_KEY: $_RECAPTCHA_KEY
  RECAPTCHA_SITE_KEY: $_RECAPTCHA_SITE_KEY
  SECRET_KEY_BASE: $_SECRET_KEY_BASE
  SENTRY_DSN: $_SENTRY_DSN

beta_settings:
  cloud_sql_instances: $_CLOUD_SQL_INSTANCES
